
package wsClient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DescriptionWSImpImplementationService", targetNamespace = "http://wsServices/", wsdlLocation = "http://localhost:8080/lab7_war_exploded/DescriptionWSImpImplementation?wsdl")
public class DescriptionWSImpImplementationService
    extends Service
{

    private final static URL DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_QNAME = new QName("http://wsServices/", "DescriptionWSImpImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab7_war_exploded/DescriptionWSImpImplementation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public DescriptionWSImpImplementationService() {
        super(__getWsdlLocation(), DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_QNAME);
    }

    public DescriptionWSImpImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public DescriptionWSImpImplementationService(URL wsdlLocation) {
        super(wsdlLocation, DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_QNAME);
    }

    public DescriptionWSImpImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public DescriptionWSImpImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DescriptionWSImpImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DescriptionWS
     */
    @WebEndpoint(name = "DescriptionWSImpImplementationPort")
    public DescriptionWS getDescriptionWSImpImplementationPort() {
        return super.getPort(new QName("http://wsServices/", "DescriptionWSImpImplementationPort"), DescriptionWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DescriptionWS
     */
    @WebEndpoint(name = "DescriptionWSImpImplementationPort")
    public DescriptionWS getDescriptionWSImpImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServices/", "DescriptionWSImpImplementationPort"), DescriptionWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return DESCRIPTIONWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
