
package wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DirectorWS", targetNamespace = "http://wsServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DirectorWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDirector", targetNamespace = "http://wsServices/", className = "wsClient.DeleteDirector")
    @ResponseWrapper(localName = "deleteDirectorResponse", targetNamespace = "http://wsServices/", className = "wsClient.DeleteDirectorResponse")
    public void deleteDirector(
        @WebParam(name = "arg0", targetNamespace = "")
        Director arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addDirector", targetNamespace = "http://wsServices/", className = "wsClient.AddDirector")
    @ResponseWrapper(localName = "addDirectorResponse", targetNamespace = "http://wsServices/", className = "wsClient.AddDirectorResponse")
    public void addDirector(
        @WebParam(name = "arg0", targetNamespace = "")
        Director arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateDirector", targetNamespace = "http://wsServices/", className = "wsClient.UpdateDirector")
    @ResponseWrapper(localName = "updateDirectorResponse", targetNamespace = "http://wsServices/", className = "wsClient.UpdateDirectorResponse")
    public void updateDirector(
        @WebParam(name = "arg0", targetNamespace = "")
        Director arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteDirectorById", targetNamespace = "http://wsServices/", className = "wsClient.DeleteDirectorById")
    @ResponseWrapper(localName = "deleteDirectorByIdResponse", targetNamespace = "http://wsServices/", className = "wsClient.DeleteDirectorByIdResponse")
    public void deleteDirectorById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsClient.Director
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDirectorById", targetNamespace = "http://wsServices/", className = "wsClient.GetDirectorById")
    @ResponseWrapper(localName = "getDirectorByIdResponse", targetNamespace = "http://wsServices/", className = "wsClient.GetDirectorByIdResponse")
    public Director getDirectorById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<wsClient.Director>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllDirectors", targetNamespace = "http://wsServices/", className = "wsClient.GetAllDirectors")
    @ResponseWrapper(localName = "getAllDirectorsResponse", targetNamespace = "http://wsServices/", className = "wsClient.GetAllDirectorsResponse")
    public List<Director> getAllDirectors();

}
