
package wsClient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MovieWSWSImpImplementationService", targetNamespace = "http://wsServices/", wsdlLocation = "http://localhost:8080/lab7_war_exploded/MovieWSWSImpImplementation?wsdl")
public class MovieWSWSImpImplementationService
    extends Service
{

    private final static URL MOVIEWSWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOVIEWSWSIMPIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName MOVIEWSWSIMPIMPLEMENTATIONSERVICE_QNAME = new QName("http://wsServices/", "MovieWSWSImpImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab7_war_exploded/MovieWSWSImpImplementation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOVIEWSWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        MOVIEWSWSIMPIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public MovieWSWSImpImplementationService() {
        super(__getWsdlLocation(), MOVIEWSWSIMPIMPLEMENTATIONSERVICE_QNAME);
    }

    public MovieWSWSImpImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOVIEWSWSIMPIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public MovieWSWSImpImplementationService(URL wsdlLocation) {
        super(wsdlLocation, MOVIEWSWSIMPIMPLEMENTATIONSERVICE_QNAME);
    }

    public MovieWSWSImpImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOVIEWSWSIMPIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public MovieWSWSImpImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MovieWSWSImpImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MovieWS
     */
    @WebEndpoint(name = "MovieWSWSImpImplementationPort")
    public MovieWS getMovieWSWSImpImplementationPort() {
        return super.getPort(new QName("http://wsServices/", "MovieWSWSImpImplementationPort"), MovieWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MovieWS
     */
    @WebEndpoint(name = "MovieWSWSImpImplementationPort")
    public MovieWS getMovieWSWSImpImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServices/", "MovieWSWSImpImplementationPort"), MovieWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOVIEWSWSIMPIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw MOVIEWSWSIMPIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return MOVIEWSWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
