
package wsClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProducerWS", targetNamespace = "http://wsServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProducerWS {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addProducer", targetNamespace = "http://wsServices/", className = "wsClient.AddProducer")
    @ResponseWrapper(localName = "addProducerResponse", targetNamespace = "http://wsServices/", className = "wsClient.AddProducerResponse")
    public void addProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        Producer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<wsClient.Producer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllProducers", targetNamespace = "http://wsServices/", className = "wsClient.GetAllProducers")
    @ResponseWrapper(localName = "getAllProducersResponse", targetNamespace = "http://wsServices/", className = "wsClient.GetAllProducersResponse")
    public List<Producer> getAllProducers();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProducer", targetNamespace = "http://wsServices/", className = "wsClient.DeleteProducer")
    @ResponseWrapper(localName = "deleteProducerResponse", targetNamespace = "http://wsServices/", className = "wsClient.DeleteProducerResponse")
    public void deleteProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        Producer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteProducerById", targetNamespace = "http://wsServices/", className = "wsClient.DeleteProducerById")
    @ResponseWrapper(localName = "deleteProducerByIdResponse", targetNamespace = "http://wsServices/", className = "wsClient.DeleteProducerByIdResponse")
    public void deleteProducerById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns wsClient.Producer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProducerById", targetNamespace = "http://wsServices/", className = "wsClient.GetProducerById")
    @ResponseWrapper(localName = "getProducerByIdResponse", targetNamespace = "http://wsServices/", className = "wsClient.GetProducerByIdResponse")
    public Producer getProducerById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateProducer", targetNamespace = "http://wsServices/", className = "wsClient.UpdateProducer")
    @ResponseWrapper(localName = "updateProducerResponse", targetNamespace = "http://wsServices/", className = "wsClient.UpdateProducerResponse")
    public void updateProducer(
        @WebParam(name = "arg0", targetNamespace = "")
        Producer arg0);

}
