
package wsClient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProducerWSImpImplementationService", targetNamespace = "http://wsServices/", wsdlLocation = "http://localhost:8080/lab7_war_exploded/ProducerWSImpImplementation?wsdl")
public class ProducerWSImpImplementationService
    extends Service
{

    private final static URL PRODUCERWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCERWSIMPIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName PRODUCERWSIMPIMPLEMENTATIONSERVICE_QNAME = new QName("http://wsServices/", "ProducerWSImpImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab7_war_exploded/ProducerWSImpImplementation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCERWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        PRODUCERWSIMPIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public ProducerWSImpImplementationService() {
        super(__getWsdlLocation(), PRODUCERWSIMPIMPLEMENTATIONSERVICE_QNAME);
    }

    public ProducerWSImpImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCERWSIMPIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public ProducerWSImpImplementationService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCERWSIMPIMPLEMENTATIONSERVICE_QNAME);
    }

    public ProducerWSImpImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCERWSIMPIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public ProducerWSImpImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProducerWSImpImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProducerWS
     */
    @WebEndpoint(name = "ProducerWSImpImplementationPort")
    public ProducerWS getProducerWSImpImplementationPort() {
        return super.getPort(new QName("http://wsServices/", "ProducerWSImpImplementationPort"), ProducerWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProducerWS
     */
    @WebEndpoint(name = "ProducerWSImpImplementationPort")
    public ProducerWS getProducerWSImpImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsServices/", "ProducerWSImpImplementationPort"), ProducerWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCERWSIMPIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw PRODUCERWSIMPIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return PRODUCERWSIMPIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
